services:
  burgerorderer:
    build: ./Containers/BurgerOrderer
    ports:
      - "3000:3000"
      - "9229:9229"  
    command: ["npm", "run", "start:debug"]
    depends_on:
      - menustore
    networks:
      - burger-network

  kitchenview:
    build: ./Containers/KitchenView
    ports:
      - "4000:4000"
      - "9230:9230" 
    command: ["npm", "run", "start:debug"]
    depends_on:
      - menustore
    networks:
      - burger-network

  menustore:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1955
      MYSQL_DATABASE: menuStore
    volumes:
      - menustore-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - burger-network

volumes:
  menustore-data:

networks:
  burger-network:
